apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
  name: ingress-service
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: multi-client-cluster-service
            port:
              number: 3000
        path: /
      - backend:
          service:
            name: multi-server-service
            port:
              number: 5000
        path: /api/
