apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres-deployment
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-deployment
  template:
    metadata:
      labels:
        app: postgres-deployment
    spec:
      volumes:
        - name: postgres-pvc-volume
          PersistentVolumeClaim:
            claimName: postgres-pvc
      containers:
      - image: postgres
        name: postgres
        volumeMounts:
        - name: postgres-pvc-volume
          mountPath: /var/lib/postgresql/data
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-env
              key: POSTGRES_PASSWORD